"""Regenerate subnetry/tools/topports.py: Nmap's 1000 most common TCP ports, most common first.

Developer tool, not needed to run Subnetry. Reads Nmap's nmap-services frequency table;
the result is the same list `nmap --top-ports 1000` scans:  python scripts/build_topports.py [path]
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "subnetry" / "tools" / "topports.py"


def main() -> None:
    src = Path(sys.argv[1] if len(sys.argv) > 1 else "/usr/share/nmap/nmap-services")
    rows = []
    for line in src.read_text().splitlines():
        if line.startswith("#") or not line.strip():
            continue
        name, port_proto, freq = line.split()[:3]
        port, proto = port_proto.split("/")
        if proto == "tcp":
            rows.append((-float(freq), int(port), name))
    rows.sort()
    lines = [f"{port} {name}" for _, port, name in rows[:1000]]
    OUT.write_text(
        '"""Nmap\'s 1000 most common TCP ports (most common first) and their service names.\n\n'
        "Generated by scripts/build_topports.py from Nmap's nmap-services frequency table, so the\n"
        "built-in scanner checks the same ports as `nmap --top-ports 1000` when Nmap isn't installed.\n"
        '"""\n\n'
        f'_DATA = """\n{chr(10).join(lines)}\n"""\n\n'
        "SERVICES: dict[int, str] = {int(p): n for p, n in (line.split() for line in _DATA.split(chr(10)) if line)}\n"
        "TOP_1000: list[int] = list(SERVICES)\n"
    )
    print(f"wrote {OUT.relative_to(ROOT)} ({len(lines)} ports)")


if __name__ == "__main__":
    main()
